openapi: 3.0.1
info:
  title: SCALE Commercial Agreements Service
  version: "0.0.4"
  description: This API allows access to CCS Commercial Agreement data. This is used both to provide information to users and to govern the behaviour of other systems for example 'Buy a Thing' and 'Contract for a Thing', where processes may differ based on the configuration of the underlying Commercial Agreement and Lot.

#  PLACEHOLDERs - to be uncommented when implemented
#  termsOfService: "http://api.crowncommercial.gov.uk/terms/"
#  contact:
#    email: "apiteam@crowncommercial.gov.uk"
#  license:
#    name: "Open Government Licence 3.0"
#    url: "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"

# Some data is explicitly omitted from the initial version of the API. Some detailed notes below but a summary here
# - Terms and conditions are not included (in MVP) as individual data items. It is assumed that a link to a t&cs document will be provided for all Agreements. To be considered post MVP.
# - 'Special Considerations' - mentioned in an email from JW, needs analysis
# - ...
# References: TDDA-009 - Agreements Service (https://docs.google.com/document/d/1PkS669G7cinFkvNI3OpxUyjoYxVWhkzYRkrTByDfRaY)
#
# TODO:
# 1. calls to manage data e.g. POST agreement, lot; PUT modifications and so on
# 2. Questions that need to be answered by suppliers on registration (for Evidence Locker) - talk to
# 3. CaT data - RFx question lists per lot
# 4. Implement security when Conclave or other Auth in place. Commented out for now
#
#security:
#  - OAuth2:
#    - read

paths:
  # No filter parameter included against API principle due to no use case for this call for MVP which would require a filter and enterprise search provides search functionality on agreements.
  /agreements:
    get:
      summary: Returns an array of all configured Commercial Agreements
      description: Returns an array of Commercial Agreement Ids, names and simple descriptions
      tags:
      - get-agreement-list
      operationId: get-agreements
      parameters:
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-correlation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-causation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-channel'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-client'
      responses:
        200:
          description: Collection of Commercial Agreement summary entities
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/ReleaseSummary'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'

  /agreements/{ca-number}:
    get:
      summary: Returns details of the specified Commercial Agreement
      description: Returns the definition of the specified Commercial Agreement
      tags:
      - get-agreement-detail
      operationId: get-agreement-detail
      parameters:
        - name: ca-number
          in: path
          description: Commercial Agreement unique 'number'
          example: RM3733
          required: true
          schema:
            type: string
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-correlation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-causation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-channel'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-client'
      responses:
        200:
          description: Commercial Agreement detail
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Release'
        404:
          description: Commercial Agreement not found
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'

  /agreements/{agreementID}/documents:
    get:
      summary: Returns details of the specified Commercial Agreement documents
      description: Returns the documents for the specified Commercial Agreement
      tags:
      - get-agreement-documents
      operationId: get-agreement-documents
      parameters:
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-correlation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-causation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-channel'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-client'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/AgreementParam'
      responses:
        200:
          description: Commercial Agreement documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Document'
        404:
          description: Commercial Agreement not found
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'
        500:
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'


 # The get-agreement-detail call explicitly omits CPV codes in the initial version. These will be added later if required. As there are potentially thousands of CPV codes it was felt that these would overwhelm the output and management of the underlying data.  Additional calls can be added to provide these if required in a similar way to the '/agreements/{ca-number}/updates' call below.


  /agreements/{agreementID}/tender/lots/{lotID}:
    get:
      summary: Returns details of the specified Lot for this Commercial Agreement
      description: Returns data about the Lot, both general information and parameters required to govern the behaviour of applications using this data
      tags:
      - get-lot-detail-for-agreement
      operationId: get-lot-details
      parameters:
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-correlation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-causation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-channel'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-client'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Params.yaml#/components/parameters/AgreementParam'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Params.yaml#/components/parameters/LotParam'
      responses:
        200:
          description: Lot details
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Lot'
        404:
          description: Commercial Agreement and/or Lot not found
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'
                
    


  /agreements/{agreementID}/tender/lots/{lotID}/suppliers:
    get:
      summary: Returns details of the suppliers for the specified Lot for this Commercial Agreement
      description: Returns the supplier list for the Lot
      tags:
      - get-lot-suppliers
      operationId: get-lot-suppliers
      parameters:
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-correlation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-causation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-channel'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-client'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Params.yaml#/components/parameters/AgreementParam'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Params.yaml#/components/parameters/LotParam'
      responses:
        200:
          description: Lot details
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Organization'
        404:
          description: Commercial Agreement and/or Lot not found
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'

  /agreements/{agreementID}/tender/lots/{lotID}/documents:
    get:
      summary: Returns details of the documents for the specified Lot for this Commercial Agreement
      description: Returns the document list for the Lot
      tags:
      - get-lot-documents
      operationId: get-lot-documents
      parameters:
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-correlation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-causation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-channel'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-client'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Params.yaml#/components/parameters/AgreementParam'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Params.yaml#/components/parameters/LotParam'
      responses:
        200:
          description: Lot documents
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Document'
        404:
          description: Commercial Agreement and/or Lot not found
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'


  /agreements/{ca-number}/updates:
    get:
      summary: Returns any updates added to the Agreement
      description: Returns updates recorded for the specified Commercial Agreement
      tags:
      - get-agreement-updates
      operationId: get-agreement-updates
      parameters:
        - name: ca-number
          in: path
          description: Commercial Agreement unique number
          example: RM3733
          required: true
          schema:
            type: string
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-correlation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-causation-id'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-channel'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/CCS_Standard_API_Params.yaml#/components/parameters/x-client'
        - $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/parameters/AgreementNumberParam'
      responses:
        200:
          description: Commercial Agreement updates
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Amendment'
        404:
          description: Commercial Agreement not found.
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/ronin1972/ccs-scale-api-definitions/master/OCDS_Schema.yaml#/components/schemas/Errors'
